// Generated by Wrangler on Thu Aug 22 2024 07:09:45 GMT-0500 (Central Daylight Time)
// by running `wrangler types`

interface Env {
	NUXT_NEXTAUTH_SECRET: string;
	NUXT_DISCORD_CLIENT_ID: string;
	NUXT_DISCORD_CLIENT_SECRET: string;
	NUXT_NEXTAUTH_URL: string;
	DISABLE_NODE_FETCH_NATIVE_WARN: string;
}
